name: Deploy Pages
on:
  push:
    paths:
      - 'pages/**'  # Trigger only on changes to the public directory
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Wrangler CLI
        run: npm install -g wrangler
      
      - name: Deploy Pages
        run: wrangler pages deploy ./ 

        env:
          CLOUDFLARE_API_TOKEN: ${{secrets.EDIT_CLOUDFLARE_WORKERS_TOKEN}}
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}